Desktop version touchup
egichuhis/Edwin-Gichuhi-Portfolio pull request #4
Opened 2023-07-11 05:57 UTC by egichuhis

Hello, please review my PR:

Changes:

- Desktop version via media queries

2023-07-11 06:45 UTC, wayungi requested changes
Hi @egichuhis , 

![image](https://user-images.githubusercontent.com/99656687/234198503-c41d0396-d5b0-4466-8ed1-959de33796fa.png)


**Congratulations on the good job done so far!** 🤝 

There are some issues that you still need to work on to go to the next project but you are almost there! 😄 

## Highlights ⚡ ⚡ 
- [ ] All Linter checks are passing ✔️ 
- [ ] Good commit messages ✔
- [ ]  Correct GitHub flow ✔️ 

## Required Changes ♻️
_Check the comments under the review._
- [ ] The title recent works on the desktop version is on one line but your implementation has it on 2 line. Please correct this. 👍🏾 
**Design**
![works2](https://github.com/egichuhis/Edwin-Gichuhi-Portfolio/assets/99656687/a9c220e9-6203-482b-a709-179bdfcbf1d6)

**Implementation**
![works1](https://github.com/egichuhis/Edwin-Gichuhi-Portfolio/assets/99656687/346f4c38-2db6-405e-8444-392510062a78)

- [ ] You have not stuck to the fonts in the Figma. I noticed the **about me** section uses the [crete round](https://fonts.google.com/specimen/Crete+Round?query=crete) font but you have not imported this font and therefore a generic san-serif  font has been used. Please import it in your css file so that it can take effect. Make sure your fonts match all through the design.

- [ ]  Your background image for this section is also sligltly mis-positioned. Please adjust the positioning to match the FIgma. 

**Design**
![title1](https://github.com/egichuhis/Edwin-Gichuhi-Portfolio/assets/99656687/bfec7f7d-bad7-4206-8663-3919a331c606)

**Impelmentation**
![title2](https://github.com/egichuhis/Edwin-Gichuhi-Portfolio/assets/99656687/7b70fcc9-e8f3-4c1f-a77b-48e796b9504a)

**MOBILE VERSION**

- [ ] Your mobile version design has become distorted abit. Kindly fix the areas of distortation below. 

- [ ] Please note the missining title in your imlpementation at 375px
**Design**
![mob1](https://github.com/egichuhis/Edwin-Gichuhi-Portfolio/assets/99656687/b25d9c69-7152-48b1-b864-451813cbe6ec)

**Implementation**
![mob2](https://github.com/egichuhis/Edwin-Gichuhi-Portfolio/assets/99656687/5d0d8f16-86b4-44f4-9b1f-064aa800f686)





## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-12 06:44 UTC, skyv26 requested changes
## Hi @egichuhis, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## STATUS: REQUIRE CHANGES 🔴 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExYTY5MTMxNDUzNWFmNjU5MmFjOWZjY2IyMDIyY2RhNWFlYmU4NjdlNCZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/Xfb7kQ0VhUIrpiuGx1/giphy.gif)

## Highlights
- Good **PR** title ✅ 
- Descriptive *PR* description ✅ 
- Implement the features ✅ 
- Linters are green ✅ 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

#### Cheers, and Happy coding!👏👏👏

## ⚠️  WARNING ⚠️ 
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="@skyv26" />
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="linkedin-skyv2022" />
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" alt="@vrma_aakash" />
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   <img src="https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white" alt="@skybrel" />
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   <img src="https://user-images.githubusercontent.com/66476329/243158690-61eb1021-fbb6-464d-b841-a09c4caa156e.png" alt="@skybrel" />
</a>

</td>
</tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-12 06:44 UTC, skyv26 commented on style.css
>    .about .title {
- [ ] Well done 👏🏻 , you did an awesome job by implementing some of the changes as per the previous code reviewer's request 👍🏻 but it seems like you haven't implemented one change which was mentioned by the previous code reviewer related to your `about` section **title**. Even I can see that you used the `crete round` font but it might be possible that you haven't added the Google font *CDN* link either in your `HTML` or `style.css`. Kindly take a look at the below image comparison for the title.

### Requirement
![image](https://user-images.githubusercontent.com/66476329/236188683-4224cc77-237d-413d-9942-91297c87687b.png)

### Design Comparison
<table>
<tr>
<th>Figma Design</th>
<th>Your Design</th>
</tr>
<tr>
<td>

![Screenshot from 2023-07-12 11-51-12](https://github.com/egichuhis/Edwin-Gichuhi-Portfolio/assets/66476329/538ca33b-0e59-4940-b3e0-695ed1cfe807)

</td>
<td>

![Screenshot from 2023-07-12 11-50-15](https://github.com/egichuhis/Edwin-Gichuhi-Portfolio/assets/66476329/33142937-6602-44fd-aca8-732cd266ca26)

</td>
</tr>
</table>

2023-07-12 07:19 UTC, amejid approved these changes
Hi @egichuhis, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Correct workflow ✔️ 
- Font issues fixed ✔️ 
- Good UI ✔️ 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-12 07:19 UTC, merged